# -*- coding: utf-8 -*-
"""Introduccion_googlecolab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dWQ2Zr1Ck_fCEstb96hrXgVle8hG54jL
"""

print ('Hello World!')

"""#Operaciones Aritmeticas

#Suma
"""

4 + 5 #Suma de literales

"""##Resta

"""

10 - 2

"""#Multiplicación

"""

4 * 5

"""
##Potencia"""

2 ** 3

"""##División"""

1 / 2

1 // 2

"""##Modulo

"""

10%2

"""##Tipos de datos y variables"""

#Variable entera
numero1 = 10
type(numero1)

numero2 = 20
resultado = numero1 + numero2
resultado

#flotantes
numero1 = 45,6
type(numero1)

print('El resultado es: ',resultado)

print('El resultado es: '+ str (resultado))

print('Hola',"como estas", resultado)

print('Hola como estas "TDA"' )

print ("Hola como estan \'TDA\'")

valor = int(input('Introduce el valor:'))

print(valor)

#numeros boleanos
valor = True
valor

type(valor)

saludo = 'Hola'
saludo

print(saludo,'Como estas',sep='-')

"""##Prioridades de los operadores"""

4 + 5 * 10

(4+5) * 10

20 / 2 * 3

1 / 2 * 3

1 //2 * 3



"""#Operadores relacionales"""

variable = 10.2
variable2 = variable  ==10.2
variable2

type (variable2)